CREATE OR REPLACE VIEW JUGADORES (DNI, NOMBRE, NICKNAME, ROL, SUELDO, TELEFONO, ANIOS_PRO, EQUIPO)
AS
SELECT M.DNI, M.NOMBRE, J.NICKNAME, J.ROL, J.SUELDO, M.TELEFONO, M.ANIOS_PRO, E.NOMBRE
FROM MIEMBRO M, JUGADOR J, EQUIPO E
WHERE M.ID_EQUIPO=E.ID
AND M.ID=J.ID_JUGADOR
WITH READ ONLY;