CREATE OR REPLACE VIEW ENTRNADOR (DNI, NOMBRE, SUELDO, TELEFONO, ANIOS_PRO, EQUIPO)
AS
SELECT M.DNI, M.NOMBRE, N.SUELDO, M.TELEFONO, M.ANIOS_PRO, E.NOMBRE
FROM MIEMBRO M, EQUIPO E, ENTRNADOR N
WHERE M.ID_EQUIPO=E.ID
AND M.ID=N.ID_ENTRENADOR
WITH READ ONLY;